use crate::addressing::Mode;

#[allow(clippy::upper_case_acronyms)]
#[derive(Debug, Clone, Copy)]
pub enum Name {
    BRK,
    ORA,
    KIL,
    SLO,
    NOP,
    ASL,
    PHP,
    ANC,
    BPL,
    CLC,
    JSR,
    AND,
    RLA,
    BIT,
    ROL,
    PLP,
    BMI,
    SEC,
    RTI,
    EOR,
    SRE,
    LSR,
    PHA,
    ALR,
    JMP,
    BVC,
    CLI,
    RTS,
    ADC,
    RRA,
    ROR,
    PLA,
    ARR,
    BVS,
    SEI,
    STA,
    SAX,
    STY,
    STX,
    DEY,
    TXA,
    XAA,
    BCC,
    AHX,
    TYA,
    TXS,
    TAS,
    SHY,
    SHX,
    LDY,
    LDA,
    LDX,
    LAX,
    TAY,
    TAX,
    BCS,
    CLV,
    TSX,
    LAS,
    CPY,
    CMP,
    DCP,
    DEC,
    INY,
    DEX,
    AXS,
    BNE,
    CLD,
    CPX,
    SBC,
    ISC,
    INC,
    INX,
    BEQ,
    SED,
}

pub struct Opcode {
    pub name: Name,
    pub size: u8,
    pub cycles: u8,
    pub cycles_page_crossed: u8,
    pub mode: Mode,
}

impl Opcode {
    #[must_use]
    pub const fn new(
        name: Name,
        size: u8,
        cycles: u8,
        cycles_page_crossed: u8,
        mode: Mode,
    ) -> Self {
        Self {
            name,
            size,
            cycles,
            cycles_page_crossed,
            mode,
        }
    }
}

pub const INSTRUCTIONS: &[Opcode] = &[
    Opcode::new(Name::BRK, 1, 7, 0, Mode::Implied), // 0x00
    Opcode::new(Name::ORA, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::SLO, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::ORA, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::ASL, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::SLO, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::PHP, 1, 3, 0, Mode::Implied),
    Opcode::new(Name::ORA, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::ASL, 1, 2, 0, Mode::Accumulator),
    Opcode::new(Name::ANC, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::NOP, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::ORA, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::ASL, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::SLO, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BPL, 2, 2, 0, Mode::Relative), // 0x10
    Opcode::new(Name::ORA, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::SLO, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::ORA, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::ASL, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::SLO, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::CLC, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::ORA, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::SLO, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::ORA, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::ASL, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::SLO, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::JSR, 3, 6, 0, Mode::Absolute), // 0x20
    Opcode::new(Name::AND, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::RLA, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::BIT, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::AND, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::ROL, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::RLA, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::PLP, 1, 4, 0, Mode::Implied),
    Opcode::new(Name::AND, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::ROL, 1, 2, 0, Mode::Accumulator),
    Opcode::new(Name::ANC, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::BIT, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::AND, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::ROL, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::RLA, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BMI, 2, 2, 0, Mode::Relative), // 0x30
    Opcode::new(Name::AND, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::RLA, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::AND, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::ROL, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::RLA, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::SEC, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::AND, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::RLA, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::AND, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::ROL, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::RLA, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::RTI, 1, 6, 0, Mode::Implied), // 0x40
    Opcode::new(Name::EOR, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::SRE, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::EOR, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::LSR, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::SRE, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::PHA, 1, 3, 0, Mode::Implied),
    Opcode::new(Name::EOR, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::LSR, 1, 2, 0, Mode::Accumulator),
    Opcode::new(Name::ALR, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::JMP, 3, 3, 0, Mode::Absolute),
    Opcode::new(Name::EOR, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::LSR, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::SRE, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BVC, 2, 2, 0, Mode::Relative), // 0x50
    Opcode::new(Name::EOR, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::SRE, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::EOR, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::LSR, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::SRE, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::CLI, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::EOR, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::SRE, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::EOR, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::LSR, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::SRE, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::RTS, 1, 6, 0, Mode::Implied), // 0x60
    Opcode::new(Name::ADC, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::RRA, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::ADC, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::ROR, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::RRA, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::PLA, 1, 4, 0, Mode::Implied),
    Opcode::new(Name::ADC, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::ROR, 1, 2, 0, Mode::Accumulator),
    Opcode::new(Name::ARR, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::JMP, 3, 5, 0, Mode::Indirect),
    Opcode::new(Name::ADC, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::ROR, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::RRA, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BVS, 2, 2, 0, Mode::Relative), // 0x70
    Opcode::new(Name::ADC, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::RRA, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::ADC, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::ROR, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::RRA, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::SEI, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::ADC, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::RRA, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::ADC, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::ROR, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::RRA, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::NOP, 2, 2, 0, Mode::Immediate), // 0x80
    Opcode::new(Name::STA, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::SAX, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::STY, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::STA, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::STX, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::SAX, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::DEY, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::NOP, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::TXA, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::XAA, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::STY, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::STA, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::STX, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::SAX, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::BCC, 2, 2, 0, Mode::Relative), // 0x90
    Opcode::new(Name::STA, 2, 6, 0, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::AHX, 2, 6, 0, Mode::IndirectY),
    Opcode::new(Name::STY, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::STA, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::STX, 2, 4, 0, Mode::ZeroPageY),
    Opcode::new(Name::SAX, 2, 4, 0, Mode::ZeroPageY),
    Opcode::new(Name::TYA, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::STA, 3, 5, 0, Mode::AbsoluteY),
    Opcode::new(Name::TXS, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::TAS, 3, 5, 0, Mode::AbsoluteY),
    Opcode::new(Name::SHY, 3, 5, 0, Mode::AbsoluteX),
    Opcode::new(Name::STA, 3, 5, 0, Mode::AbsoluteX),
    Opcode::new(Name::SHX, 3, 5, 0, Mode::AbsoluteY),
    Opcode::new(Name::AHX, 3, 5, 0, Mode::AbsoluteY),
    Opcode::new(Name::LDY, 2, 2, 0, Mode::Immediate), // 0xA0
    Opcode::new(Name::LDA, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::LDX, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::LAX, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::LDY, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::LDA, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::LDX, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::LAX, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::TAY, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::LDA, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::TAX, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::LAX, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::LDY, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::LDA, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::LDX, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::LAX, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::BCS, 2, 2, 0, Mode::Relative), // 0xB0
    Opcode::new(Name::LDA, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::LAX, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::LDY, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::LDA, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::LDX, 2, 4, 0, Mode::ZeroPageY),
    Opcode::new(Name::LAX, 2, 4, 0, Mode::ZeroPageY),
    Opcode::new(Name::CLV, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::LDA, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::TSX, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::LAS, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::LDY, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::LDA, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::LDX, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::LAX, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::CPY, 2, 2, 0, Mode::Immediate), // 0xC0
    Opcode::new(Name::CMP, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::DCP, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::CPY, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::CMP, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::DEC, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::DCP, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::INY, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::CMP, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::DEX, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::AXS, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::CPY, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::CMP, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::DEC, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::DCP, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BNE, 2, 2, 0, Mode::Relative), // 0xD0
    Opcode::new(Name::CMP, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::DCP, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::CMP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::DEC, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::DCP, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::CLD, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::CMP, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::DCP, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::CMP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::DEC, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::DCP, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::CPX, 2, 2, 0, Mode::Immediate), // 0xE0
    Opcode::new(Name::SBC, 2, 6, 0, Mode::IndirectX),
    Opcode::new(Name::NOP, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::ISC, 2, 8, 0, Mode::IndirectX),
    Opcode::new(Name::CPX, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::SBC, 2, 3, 0, Mode::ZeroPage),
    Opcode::new(Name::INC, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::ISC, 2, 5, 0, Mode::ZeroPage),
    Opcode::new(Name::INX, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::SBC, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::SBC, 2, 2, 0, Mode::Immediate),
    Opcode::new(Name::CPX, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::SBC, 3, 4, 0, Mode::Absolute),
    Opcode::new(Name::INC, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::ISC, 3, 6, 0, Mode::Absolute),
    Opcode::new(Name::BEQ, 2, 2, 0, Mode::Relative), // 0xF0
    Opcode::new(Name::SBC, 2, 5, 1, Mode::IndirectY),
    Opcode::new(Name::KIL, 1, 0, 0, Mode::Implied),
    Opcode::new(Name::ISC, 2, 8, 0, Mode::IndirectY),
    Opcode::new(Name::NOP, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::SBC, 2, 4, 0, Mode::ZeroPageX),
    Opcode::new(Name::INC, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::ISC, 2, 6, 0, Mode::ZeroPageX),
    Opcode::new(Name::SED, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::SBC, 3, 4, 1, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 1, 2, 0, Mode::Implied),
    Opcode::new(Name::ISC, 3, 7, 0, Mode::AbsoluteY),
    Opcode::new(Name::NOP, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::SBC, 3, 4, 1, Mode::AbsoluteX),
    Opcode::new(Name::INC, 3, 7, 0, Mode::AbsoluteX),
    Opcode::new(Name::ISC, 3, 7, 0, Mode::AbsoluteX),
];
